evaluation:
  clue_discont: 0.1
  full_answer: 1.0
  half_answer: 0.5
  no_answer: 0.0
  wrong_answer: 0.0
game:
  clues_number: 10
  clues_strategy: new_next
  infinite_repeats: false
  repeats_number: 5
  rounds_number: 10
  sample_duration: 1.0
players:
- name: fake
  path: /
sampling:
  from_: 2.0
  strategy: normalized
  to_finish: 3
selection:
  strategy: naive
typing:
  enabled: true
  max_delay: 0.1
  min_delay: 0.01
